### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by wcaleb**

### CODE REVIEW

**Comment by rzach** [comment]
Thanks -- but what was the typo? I don't see a change.

**Comment by wcaleb** [comment]
"it makes is easy" --> "it makes IT easy"

**Comment by rzach** [comment]
Ah! diff didn't highlight it for some reason.

**Comment by wcaleb** [comment]
It could be that it only highlights the line to a certain character 
length. It shows up when you click on the "rich diff" icon next to 
"View" in the upper right corner of the "Files changed" tab.

**Pull request merged**
